### ISSUE TITLE
HERO section

### ISSUE THREAD

**Issue by TanvirAlam** [AkijVenture/akij-turborepo#35]
I need sample of this in Figma

- Remove the coke can and replace it with mojo bottle png
- replace the logo with akij food and beverage logo (top left hand corner)
- keep everything else same, do not change anything else
- change `Diat coke` heading to `Mojo something`
- also look at the light heading too right hand
- Remove the orange circle

![Image](https://user-images.githubusercontent.com/3250040/209227112-d43b7481-7ba1-4cf1-bc1f-83124d37fe3e.png)

**Comment by morshlab** [comment]
https://www.figma.com/proto/SIwVcRNdqJMd10EV21WIbR/AVL-website-(hero%2Bscratch-card-%2B-font%2Bnav%2B-etc..)?node-id=274%3A1599&scaling=scale-down&page-id=0%3A1&starting-point-node-id=274%3A1599&show-proto-sidebar=1

**Comment by morshlab** [comment]
![Image](https://user-images.githubusercontent.com/54287452/212045637-d4f3c375-49ef-4b28-a6ca-21cce601a5c1.png)
![Image](https://user-images.githubusercontent.com/54287452/212045639-9ddf2e23-4f29-4c78-af38-60c4b930024a.png)
![Image](https://user-images.githubusercontent.com/54287452/212045638-d7cfed1c-90aa-4ce8-882c-093312d116e6.png)

**Comment by TanvirAlam** [comment]
Since we have Finalized it, now we work on this #34
