### ISSUE TITLE
Industry Section

### ISSUE THREAD

**Issue by TanvirAlam** [AkijVenture/akij-turborepo#83]
Related to #78 

![Image](https://user-images.githubusercontent.com/3250040/211216772-7ab1fff3-2d20-4586-8759-20493f16a723.png)

**Comment by TanvirAlam** [comment]
Make sure design stays the same and change the image to any akij product.

This is only DESIGN, create a component `IndustrySection`, sure you add to `akij-food-beverage/src/pages/index.tsx` in the main section

Live Demo: https://nefa.vercel.app/#navbar

**Comment by urmirahman** [comment]
@morshlab If you need any help let  us ( @urmirahman and @mohiandipta ) know.
